/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerfinal;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDACAMES
 */
public class Interface extends javax.swing.JFrame {

    TadPila m = new TadPila();
    DefaultTableModel n = new DefaultTableModel();

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        //agregando las columnas a la tabla de datos
        n.addColumn("Modelo");
        n.addColumn("Placa");
        n.addColumn("Tipo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextPlaca = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BotonPop = new javax.swing.JButton();
        BotonPush = new javax.swing.JButton();
        BotonVaciar = new javax.swing.JButton();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TipoCarro = new javax.swing.JComboBox<>();
        ModeloCarro = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(722, 439));
        setSize(new java.awt.Dimension(72222, 722222));
        getContentPane().setLayout(null);

        jLabel1.setText("Modelo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 60, 14);

        jLabel2.setText("Placa: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 70, 14);

        jLabel3.setText("Tipo: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 60, 14);

        TextPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TextPlaca);
        TextPlaca.setBounds(100, 120, 90, 16);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Modelo", "Placa", "Tipo"
            }
        ));
        jScrollPane4.setViewportView(Tabla);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 240, 470, 90);

        BotonPop.setText("Despachar");
        BotonPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPopActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPop);
        BotonPop.setBounds(230, 120, 110, 23);

        BotonPush.setText("Agregar");
        BotonPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPushActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPush);
        BotonPush.setBounds(230, 70, 110, 23);

        BotonVaciar.setText("Vaciar");
        BotonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVaciarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVaciar);
        BotonVaciar.setBounds(230, 170, 110, 23);

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("Primero");
        getContentPane().add(b1);
        b1.setBounds(520, 240, 110, 14);

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("Ultimo");
        getContentPane().add(b2);
        b2.setBounds(520, 260, 120, 14);

        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setText("Cantidad");
        getContentPane().add(b3);
        b3.setBounds(520, 280, 130, 14);

        b4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b4.setText("Vacio");
        getContentPane().add(b4);
        b4.setBounds(520, 320, 130, 14);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("PETITA - MOI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 84, 18);

        jLabel6.setText("Parqueadero");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 30, 100, 16);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel7.setText("Bienvenidos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(277, 354, 88, 26);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(543, 360, 120, 23);

        TipoCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camioneta", "Camion", "Bus" }));
        getContentPane().add(TipoCarro);
        TipoCarro.setBounds(100, 170, 90, 20);

        ModeloCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Renault", "Aveo", "Chevrolet", "Ford", "Toyota", "Hyundai", "BMW" }));
        getContentPane().add(ModeloCarro);
        ModeloCarro.setBounds(100, 70, 90, 20);

        jButton3.setText("Abrir Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 70, 110, 23);

        jButton4.setText("Ver Pila");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 120, 110, 23);

        jButton5.setText("Movimientos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(390, 170, 110, 23);

        jButton6.setText("Funcionamiento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(530, 20, 140, 23);

        jButton7.setText("Import");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 20, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Placa: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 100, 80, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(570, 90, 70, 30);

        jButton2.setText("Despachar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 130, 130, 23);

        jButton8.setText("Log's");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 360, 90, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANDACAMES\\Documents\\NetBeansProjects\\TallerFinal\\src\\White-Car-Background-Wallpaper.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 720, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPopActionPerformed
// este metodo solo sacara el auto en el tope 
        if (m.Contador() > 0) {
            m.Pop();

            int valor = 0;
            int horas = Integer.parseInt(JOptionPane.showInputDialog("Cantidad de horas"));
            String Tipo = JOptionPane.showInputDialog("Digite tipo de carro");
            if (Tipo.equals("Auto") || Tipo.equals("auto")) {
                valor = horas * 2300;
            } else {
                if (Tipo.equals("Camioneta") || Tipo.equals("camioneta")) {
                    valor = horas * 3500;
                } else {
                    if (Tipo.equals("Bus") || Tipo.equals("bus")) {
                        valor = horas * 5000;
                    } else {
                        if (Tipo.equals("Camion") || Tipo.equals("camion")) {
                            valor = horas * 7000;
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Su total a pagar es: " + valor);
            JOptionPane.showMessageDialog(null, "Ha salido un auto");
            try {
                actualizar();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_BotonPopActionPerformed

    private void BotonPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPushActionPerformed
        // TODO add your handling code here:   
        //int p=0;
        if (!TextPlaca.getText().equals("")) {
            /*
            if (m.Contador() > 0) {
                for (int i = 0; i < m.Contador(); i++) {
                    if (TextTipo.getText().equals("auto")) {
                        p = 2300;
                        m.qCarro(i).setValor(p);
                    } else {
                        if (TextTipo.getText().equals("camioneta")) {
                            p = 3500;
                             m.qCarro(i).setValor(p);
                        } else {
                            if (TextTipo.getText().equals("bus")) {
                                p = 5000;
                                 m.qCarro(i).setValor(p);
                            } else {
                                if (TextTipo.getText().equals("camion")) {
                                    p = 7000;
                                     m.qCarro(i).setValor(p);
                                }
                            }
                        }
                    } 
                    
                }
            }*/
            //Se toman los datos digitados en los textfield y se asignan al constructor de la clase Carro(objeto)
            String Mensaje="Ha llegado el Carro con placa: "+TextPlaca.getText()+"  L  ";
            m.Push(new Carro(ModeloCarro.getSelectedItem().toString(), TextPlaca.getText(), TipoCarro.getSelectedItem().toString(), 'L',Mensaje));
            JOptionPane.showMessageDialog(null, "Ha llegado un auto");
            
            try {
                actualizar();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BotonPushActionPerformed

    private void BotonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVaciarActionPerformed
        // TODO add your handling code here:
        if (!TextPlaca.getText().equals("")) {
            m.VaciarFila();
            try {
                actualizar();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_BotonVaciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Archivo arc = new Archivo();
        try {
            JOptionPane.showMessageDialog(null, "====== TEXTO DEL ARCHIVO ======" + "\n" + arc.leerArchivo("Aautos.txt"));
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Archivo arc = new Archivo();
        try {
            JOptionPane.showMessageDialog(null, "====== TEXTO DEL ARCHIVO ======" + "\n" + arc.leerArchivo("Movimientos.txt"));
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //mostramos los elementos de la pila para verificar si se han guardado correctamente
        for (int i = 0; i < m.Contador(); i++) {
            JOptionPane.showMessageDialog(null, "Marca: " + m.qCarro(i).getMarca() + " Placa : " + m.qCarro(i).getPlaca() + "\n");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//Se cargan los datos del archivo autos.txt a la pila ya que son 11 no colocamos un condicional para que solo permita agregar una vez
//asi evitamos errores ya que la pila tiene un limite de 20 autos
        if (m.Contador() == 0) {
            Archivo arc = new Archivo();
            try {
                arc.CargarArchivo("autos.txt", m);
                actualizar();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (m.Contador() >= 10) {
                JOptionPane.showMessageDialog(null, "Ya se han importado los datos: la pila no puede pasar su limite");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Archivo arc = new Archivo();
        try {
            JOptionPane.showMessageDialog(null, "============  TEXTO DEL ARCHIVO ===========" + "\n" + arc.leerArchivo("Funcionamiento.txt"));
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
       
        for (int i = 0; i < m.Contador(); i++) {
            //comparacion de la placa digitada con las de la pila para el calculo del valor (Carro a sacar)
            if (m.qCarro(i).getPlaca().equals(jTextField1.getText())) {
                int valor = 0;
                int horas = Integer.parseInt(JOptionPane.showInputDialog("Cantidad de horas"));
                String Tipo = m.qCarro(i).getTipo();
                if (Tipo.equals("Auto") || Tipo.equals("auto")) {
                    valor = horas * 2300;
                } else {
                    if (Tipo.equals("Camioneta") || Tipo.equals("camioneta")) {
                        valor = horas * 3500;
                    } else {
                        if (Tipo.equals("Bus") || Tipo.equals("bus")) {
                            valor = horas * 5000;
                        } else {
                            if (Tipo.equals("Camion") || Tipo.equals("camion")) {
                                valor = horas * 7000;
                            }
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, "Su total a pagar es: " + valor);
                 m.despachar(jTextField1.getText());
                JOptionPane.showMessageDialog(null, "Ha salido un auto");
            }
        }

        try {
            actualizar();//el metodo actualizar maneja archivos por tanto pueden ocurrir errores de entrada salida
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Archivo arc = new Archivo();
        try {
            JOptionPane.showMessageDialog(null, "====== TEXTO DEL ARCHIVO ======" + "\n" + arc.leerArchivo("Mensajes.txt"));
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    public void borrartabla() {
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

    }

    public void actualizar() throws IOException {

        borrartabla();
        if (m.Contador() > 0) {
            for (int i = 0; i < m.Contador(); i++) {
                //Asignar vista a la tabla
                String fila[] = new String[3];
                fila[0] = m.qCarro(i).getMarca();
                fila[1] = m.qCarro(i).getPlaca();
                fila[2] = m.qCarro(i).getTipo();
                n.addRow(fila);
            }
            Tabla.setModel(n);
            //Guardado en Archivos
            Archivo arc = new Archivo();
            arc.guardarArchivo(m);
            arc.guardarArchivo2(m);
            arc.GuardarMensajes(m);
            JOptionPane.showMessageDialog(null, "Grabado");
        }

        b4.setText("Vacio:   " + m.coco());
        b3.setText("Elementos:  " + m.Contador() + "/20");
        if (m.Contador() == 0) {
            b1.setText("Primero:  no hay");
            b2.setText("Ultimo:  no hay");
        } else {

            b1.setText("Primero:  " + m.Primero().getPlaca());
            b2.setText("Ultimo: " + m.Ultimo().getPlaca());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPop;
    private javax.swing.JButton BotonPush;
    private javax.swing.JButton BotonVaciar;
    public static javax.swing.JComboBox<String> ModeloCarro;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextPane TextPlaca;
    public static javax.swing.JComboBox<String> TipoCarro;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
